version: '3'
services:
  webapp1:
    image: yuni2/sample-webapp:latest
    environment:
      - ENV=test
    ports:
      - "8081:3000"
  webapp2:
    image: yuni2/sample-webapp:latest
    environment:
      - ENV=dev
    ports:
      - "8082:3000"
  webapp3:
    image: yuni2/sample-webapp:latest
    environment:
      - ENV=preprod
    ports:
      - "8083:3000"
  webapp4:
    image: yuni2/sample-webapp:latest
    environment:
      - ENV=prod
    ports:
      - "8084:3000"